export default [
  {
    number: "001", // 类型序号
    code: "03708", // 课程代码
    name: "中国近代史纲要", // 课程名称
    credit: 2, // 学分
    type: "必考", // 类型
    way: "笔试", // 考试方式
    status: "", // 状态
    bookName: "中国近代史纲要/中国近代史纲要自学考试学习读本", // 教材名称
    editor: "本书编写组/李捷  王顺生", // 主编
    press: "高等教育出版社/高等教育出版社", // 出版社
    edition: "2021年版/2018年版", // 版次
    timeList: ["4.15 9:00"],
  },
  {
    number: "002",
    code: "03709",
    name: "马克思主义基本原理概论",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "马克思主义基本原理/马克思主义基本原理概论自学考试学习读本",
    editor: "本书编写组/卫兴华  赵家祥",
    press: "高等教育出版社/北京大学出版社",
    edition: "2021年版/2018年版",
    timeList: ["4.15 14:30"],
  },
  {
    number: "003",
    code: "00015",
    name: "英语(二)",
    credit: 14,
    type: "必考",
    way: "笔试",
    status: "准备中",
    bookName: "英语(二)自学教程",
    editor: "张敬源  张虹",
    press: "外语教学与研究出版社",
    edition: "2012年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "004",
    code: "02628",
    name: "管理经济学",
    credit: 5,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "管理经济学",
    editor: "陈建萍",
    press: "中国人民大学出版社",
    edition: "2018年版",
    timeList: ["4.16 9:00"],
  },
  {
    number: "005",
    code: "00910",
    name: "网络经济与企业管理",
    credit: 6,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "网络经济与企业管理",
    editor: "李凤云",
    press: "辽宁教育出版社",
    edition: "2007年版",
    timeList: ["4.15 9:00"],
  },
  {
    number: "006",
    code: "02375",
    name: "运筹学基础",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "运筹学基础",
    editor: "张学群  崔越",
    press: "经济科学出版社",
    edition: "2002年版",
    timeList: ["4.15 9:00"],
  },
  {
    number: "007",
    code: "02323",
    name: "操作系统概论",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "操作系统概论",
    editor: "张琼声",
    press: "机械工业出版社",
    edition: "2016年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "008",
    code: "02142",
    name: "数据结构导论",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "准备中",
    bookName: "数据结构导论",
    editor: "郑诚",
    press: "外语教学与研究出版社",
    edition: "2012年版",
    timeList: ["4.15 9:00"],
  },
  {
    number: "009",
    code: "04735",
    name: "数据库系统原理",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "数据库系统原理",
    editor: "黄靖",
    press: "机械工业出版社",
    edition: "2018年版",
    timeList: ["4.15 14:30"],
  },
  {
    number: "010",
    code: "04741",
    name: "计算机网络原理",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "计算机网络原理",
    editor: "李全龙",
    press: "机械工业出版社",
    edition: "2018年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "011",
    code: "04737",
    name: "C++程序设计",
    credit: 3,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "C++程序设计",
    editor: "辛运帏",
    press: "机械工业出版社",
    edition: "2019年版",
    timeList: ["4.16 9:00"],
  },
  {
    number: "012",
    code: "03173",
    name: "软件开发工具",
    credit: 5,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "软件开发工具",
    editor: "方美琪  陈禹  蒋洪讯",
    press: "机械工业出版社",
    edition: "2011年版",
    timeList: ["4.16 9:00"],
  },
  {
    number: "013",
    code: "04757",
    name: "信息系统开发与管理",
    credit: 5,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "信息系统开发与管理",
    editor: "刘世峰",
    press: "机械工业出版社",
    edition: "2011年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "014",
    code: "02378",
    name: "信息资源管理",
    credit: 4,
    type: "必考",
    way: "笔试",
    status: "",
    bookName: "信息资源管理",
    editor: "武刚",
    press: "机械工业出版社",
    edition: "2010年版",
    timeList: ["4.15 9:00"],
  },
  {
    number: "015",
    code: "11393",
    name: "计算机信息管理课程实验",
    credit: 5,
    type: "必考",
    way: "实践考核",
    status: "",
    bookName: "",
    editor: "",
    press: "",
    edition: "",
  },
  {
    number: "016",
    code: "07999",
    name: "毕业设计",
    credit: "不计学分",
    type: "必考",
    way: "实践考核",
    status: "",
    bookName: "",
    editor: "",
    press: "",
    edition: "",
  },
  {
    number: "201",
    code: "02382",
    name: "管理信息系统",
    credit: 4,
    type: "加考",
    way: "笔试",
    status: "",
    bookName: "管理信息系统",
    editor: "杨一平  卢山",
    press: "机械工业出版社",
    edition: "2017年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "201",
    code: "02383",
    name: "管理信息系统",
    credit: 1,
    type: "加考",
    way: "实践考核",
    status: "",
    bookName: "管理信息系统",
    editor: "杨一平  卢山",
    press: "机械工业出版社",
    edition: "2017年版",
    timeList: ["4.16 14:30"],
  },
  {
    number: "202",
    code: "02384",
    name: "计算机原理",
    credit: 4,
    type: "加考",
    way: "笔试",
    status: "",
    bookName: "计算机原理",
    editor: "倪继烈",
    press: "外语教学与研究出版社",
    edition: "2012年版",
    timeList: ["4.15 14:30"],
  },
  {
    number: "231",
    code: "00024",
    name: "普通逻辑",
    credit: 4,
    type: "加考",
    way: "笔试",
    status: "",
    bookName: "普通逻辑",
    editor: "杜国平",
    press: "高等教育出版社",
    edition: "2010年版",
    timeList: ["4.15 9:00"],
  },
  {
    number: "232",
    code: "05679",
    name: "宪法学",
    credit: 4,
    type: "加考",
    way: "笔试",
    status: "",
    bookName: "宪法学",
    editor: "胡锦光",
    press: "北京大学出版社",
    edition: "2019年版",
    timeList: ["4.15 9:00"],
  },
];
